### ISSUE TITLE
jp.query return Uncaught TypeError: jp.query is not a function

### ISSUE THREAD

**Issue by mgiana** [dchester/jsonpath#124]
Since upgrading to 1.0.1 from npmjs the following snippet creates an error, which used to work

import * as jp from "jsonpath";

jp.query(mapObj.mapData.source, "$..authentication.type");

where mapObj.mapData.source is a json obj.

Changing to (new jp.JSONPath()).query(mapObj.mapData.source, "$..authentication.type"); finds the query function.

Regards
Marco

**Comment by jtonic** [comment]
Hi,

For me, using jsonpath in a chrome extension, it worked like below:

```javascript
import "jsonpath";
jsonpath.query(cities, "$..name");
```

Note: Somehow, in chrome extensions, the `import * as jp from ...` doesn't work for non-es6 modules.

**Comment by indSantosh** [comment]
@jtonic , thanks a lot.
I have been struggling for a long time, thanks a lot
